### ISSUE TITLE
WHMCS Invoice page shows error

### ISSUE THREAD

**Issue by Philipinho** [coingate/whmcs-plugin#1]
Whenever i activate CoinGate payment module, the WHMCS invoice page shows error, if i deactivate CoinGate it shows normally. WHMCS 7x

**Comment by rytisbitcoin** [comment]
Do you use any other WHMCS plugins, especially ones which modify the checkout process?

Which exact version of WHMCS you are using?

Can you please attach a screenshot if the error you are getting?

**Comment by arnasfomenko** [comment]
We have successfully tested our plugin with WHMCS version 7.x and it is working perfectly.

 Please check your other plugins compatibility.
